<?php

namespace AppBundle\Repository;

use AppBundle\Controller\AlbumController;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste alphabetique des albums
     * @uses AlbumController::newAction()
     * @uses AlbumController::editAction()
     */
    public function findListASC()
    {
        return $this->liste()->getQuery()->getResult();
    }

    /**
     * Liste des albums
     */
    public function liste()
    {
        return $this->createQueryBuilder('a')
                    ->orderBy('a.titre', 'ASC')
            ;
    }
}
