<?php

namespace AppBundle\Repository;

use AppBundle\Controller\DistributeurController;

/**
 * DistributeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistributeurRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste par ordre alphabetique des distrbuteurs
     * @uses DistributeurController::newAction()
     * @uses DistributeurController::editAction()
     */
    public function findListAsc()
    {
        return $this->createQueryBuilder('d')
                    ->orderBy('d.nom', 'ASC')
                    ->getQuery()->getResult()
            ;
    }

    /**
     * Liste des distributeurs utilisé dans la vente (VenteType)
     */
    public function liste()
    {
        return $this->createQueryBuilder('d')->orderBy('d.nom', 'ASC');
    }
}
