<?php

namespace AppBundle\Repository;

use AppBundle\Controller\StickageController;

/**
 * StickageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StickageRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste des albums a sticker
     * @uses StickageController::newAction()
     */
    public function findToStickage($album)
    {
        return $this->createQueryBuilder('s')
                    ->innerJoin('s.album', 'a')
                    ->where('a.slug = :album')
                    ->andWhere('a.brut <> 0 OR a.sticke <> 0')
                    ->setParameter('album', $album)
                    ->getQuery()->getResult()
            ;
    }
}
