<?php

namespace AppBundle\Repository;

use AppBundle\Controller\StockageController;

/**
 * StockageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockageRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Liste des approvisionnements de l'album
     * @uses StockageController::newAction()
     */
    public function findApprovisionnement($album)
    {
        return $this->createQueryBuilder('s')
                    ->leftJoin('s.album', 'a')
                    ->where('a.slug = :album')
                    ->setParameter('album', $album)
                    ->getQuery()->getResult()
            ;
    }
}
